services:
  laravel:
    image: laravel:proy
    build: builds/laravel
    container_name: laravel
    volumes:
      - ./web:/var/www/html/
    ports:
     - 8000:8000
  database:
    image: mysql:8.0.39
    container_name: mysql
    restart: always
    env_file:
      .env
    volumes:
      - ./database:/var/lib/mysql/
    networks:
      - proyectnet
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - proyectnet
    env_file:
      .env
