FROM php:8.1-fpm

COPY conf/php.ini /usr/local/etc/php/conf.d/php.ini
COPY util/install_composer.sh /usr/local/bin/install_composer.sh

RUN apt-get update && \
	apt-get install -y libzip-dev && \
	docker-php-ext-configure pdo_mysql && \
	docker-php-ext-install pdo_mysql && \
	docker-php-ext-configure zip && \
	docker-php-ext-install zip && \
	sh /usr/local/bin/install_composer.sh

WORKDIR /var/www/html

CMD [ "php", "artisan", "serve", "--host", "0.0.0.0", "--port=8000"]
